# database/generators/data.py

MILKS = [
    {
        "template": "MILK",
        "name": "Whole Milk 1L",
        "name_ar": "حليب كامل الدسم 1 لتر",
        "brand": "FreshFarm",
        "price": 4.99,
        "ingredients": "Pasteurized whole milk",
        "allergens": "Milk",
    },
    {
        "template": "LOW_FAT_MILK",
        "name": "Low Fat Milk 1L",
        "name_ar": "حليب قليل الدسم 1 لتر",
        "brand": "FreshFarm",
        "price": 5.49,
        "ingredients": "Low-fat milk",
        "allergens": "Milk",
    },
    {
        "template": "SKIM_MILK",
        "name": "Skim Milk 1L",
        "name_ar": "حليب خالي الدسم 1 لتر",
        "brand": "FreshFarm",
        "price": 5.79,
        "ingredients": "Skim milk",
        "allergens": "Milk",
    },
    {
        "template": "LACTOSE_FREE_MILK",
        "name": "Lactose-Free Milk",
        "name_ar": "حليب خالي من اللاكتوز",
        "brand": "FreshFarm",
        "price": 6.99,
        "ingredients": "Lactose-free milk",
        "allergens": "Milk",
    },
    {
        "template": "PLANT_MILK",
        "name": "Almond Milk",
        "name_ar": "حليب اللوز",
        "brand": "Alpro",
        "price": 9.49,
        "ingredients": "Water, Almonds",
        "allergens": "Tree Nuts",
    },
    {
        "template": "PLANT_MILK",
        "name": "Oat Milk",
        "name_ar": "حليب الشوفان",
        "brand": "Oatly",
        "price": 9.99,
        "ingredients": "Water, Oats",
        "allergens": "Gluten",
    },
    {
        "template": "PLANT_MILK",
        "name": "Soy Milk",
        "name_ar": "حليب الصويا",
        "brand": "Alpro",
        "price": 8.99,
        "ingredients": "Water, Soybeans",
        "allergens": "Soy",
    },
]